version: '3'

services:
 db:
  image: image_medical_manager:latest
  volumes:
   - dbstorage: /var/lib/image_medical_manager
  ports:
   - "1433:1433"
  restart: always
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=123

 mvc:
  build:
   context: .
  depends_on:
   - db
  ports:
   - "6001:80"
  restart: always
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - DB
     
